### ISSUE TITLE
Running ClamAv as a daemon

### ISSUE THREAD

**Issue by shaliniajay** [clamwin/clamav#1]
Hi
I am configuring ClamAv to scan my files uploaded to .Net application on demand. 
I have completed other steps.It can scan the directories with clamscan.exe.
But ,running the clamd install ,it is not starting clamAv as service. It is reading the clamd.conf fine.

I have just copied the clamd.conf from samples and removed the Example. Do I need to do some other changes?

Thanks

**Comment by sherpya** [comment]
My setup is:

- import `clamav.reg` file
- create `c:\clamav` and `c:\clamav\db`
- put executables in `c:\clamav'
- create `freshclam.conf` in `c:\clamav`
- create `clamd.conf` in `c:\clamav'
- install the service with (in Administrator cmd prompt): `clamd.exe --install`
- launch `freshclam.exe` to download the virus database

my `freshclam.conf`:

```
DatabaseMirror database.clamav.net
DNSDatabaseInfo current.cvd.clamav.net
```

my `clamd.conf`:

```
TCPSocket 3310
TCPAddr 127.0.0.1
MaxThreads 2
LogFile c:\Clamav\clamd.log
DatabaseDirectory c:\clamav\db
```

finally start the service with `net start clamd`

**Comment by r1bnc** [comment]
This could be unrelated but, due to Clamwin being not updated since 0.99.4. 

I would like to ask what is the difference of this repository and this https://github.com/clamwin/clamav-win32/ repo?
Can you add a documentation on what are the changes, and your development environment, and how to compile this repo? VS2019? mingw?
Is this repo being used in the ClamWin project? or is it the clamav-win32 repo?

I may be interested in helping porting newer version of ClamAV, but currently I do not have the capability to use VS2019 or VS2017 (30GB disk space is too large for me, as I only have around 5 GB free space) and eventually help in maintaining ClamWin.

Also, what is the difference between the official clamav.net windows binary that can be found here https://www.clamav.net/downloads#collapseWin32
All I know is that version does not work on Windows XP and below.

Thank you
